### ISSUE TITLE
PG driver has been removed from the base image, support to be added

### ISSUE THREAD

**Issue by shamanthchandra-yb** [yugabyte/debezium-connector-yugabytedb#43]
**Connector version:** quay.io/yugabyte/debezium-connector:1.7.0.8

**Steps:**
1. Setup CDC with postgresql sink connector
2. Try to run a workload

**Observation:**
Below log is seen in connector

```
Unable to connect to database on attempt 1/3. Will retry in 10000 ms.  [io.confluent.connect.jdbc.util.CachedConnectionProvider]
java.sql.SQLException: No suitable driver found for jdbc:postgresql://10.9.3.93:5432/postgres?user=postgres&password=postgres
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:239)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:80)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:52)
	at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:64)
	at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:84)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:582)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:330)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

As per discussion with @vaibhav-yb debezium removed the PG driver from their base image and he is working on it. This is to track the same.

**Comment by vaibhav-yb** [comment]
Closing this as it has been fixed in the PR #44
