### ISSUE TITLE
snapshot.mode=initial not working properly

### ISSUE THREAD

**Issue by codecrack3** [yugabyte/debezium-connector-yugabytedb#7]
I created a connector with snapshot mode set to initial. However, it throws an exception and does not work properly with a snapshot of the current table. Please assist me in resolving this issue.

My config
`{
  "name": "ybconnect",
  "config": {
    "connector.class": "io.debezium.connector.yugabytedb.YugabyteDBConnector",
    "database.hostname": "{IP}",
    "database.port": "5433",
    "database.master.addresses": "{IP}:7100",
    "database.streamid": "f532f5ccdf3e4f3d94f4a22a5faeebca",
    "database.user": "xxx",
    "database.password": "xxx",
    "database.dbname": "xxx",
    "database.server.name": "yugabyteDB150",
    "snapshot.mode": "initial"
  }
}`
Exception:

`2022-06-23 05:28:32,203 INFO   YugabyteDB|yugabyteDB150|snapshot  Metrics registered   [io.debezium.pipeline.ChangeEventSourceCoordinator]
2022-06-23 05:28:32,204 INFO   YugabyteDB|yugabyteDB150|snapshot  Context created   [io.debezium.pipeline.ChangeEventSourceCoordinator]
2022-06-23 05:28:32,205 INFO   YugabyteDB|yugabyteDB150|snapshot  Taking initial snapshot for new datasource   [io.debezium.connector.yugabytedb.snapshot.InitialSnapshotter]
2022-06-23 05:28:32,206 INFO   YugabyteDB|yugabyteDB150|snapshot  According to the connector configuration data will be snapshotted   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,206 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot step 1 - Preparing   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,207 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot step 2 - Determining captured tables   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,208 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot step 3 - Locking captured tables []   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,208 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot step 4 - Determining snapshot offset   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,208 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot step 5 - Reading structure of captured tables   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,208 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot step 6 - Persisting schema history   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,208 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot step 7 - Snapshotting data   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,209 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshotting contents of 0 tables while still in transaction   [io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource]
2022-06-23 05:28:32,209 INFO   YugabyteDB|yugabyteDB150|snapshot  Snapshot - Final stage   [io.debezium.pipeline.source.AbstractSnapshotChangeEventSource]
2022-06-23 05:28:32,209 ERROR  YugabyteDB|yugabyteDB150|snapshot  Producer failure   [io.debezium.pipeline.ErrorHandler]
io.debezium.DebeziumException: java.lang.NullPointerException
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:79)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:118)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.createDataEvents(YugabyteDBSnapshotChangeEventSource.java:202)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:160)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:31)
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:70)
        ... 6 more
2022-06-23 05:28:32,209 INFO   YugabyteDB|yugabyteDB150|snapshot  Connected metrics set to 'false'   [io.debezium.pipeline.metrics.StreamingChangeEventSourceMetrics]
2022-06-23 05:28:32,682 INFO   ||  WorkerSourceTask{id=ybconnect-0} Committing offsets   [org.apache.kafka.connect.runtime.WorkerSourceTask]
2022-06-23 05:28:32,682 INFO   ||  WorkerSourceTask{id=ybconnect-0} flushing 0 outstanding messages for offset commit   [org.apache.kafka.connect.runtime.WorkerSourceTask]
2022-06-23 05:28:32,683 ERROR  ||  WorkerSourceTask{id=ybconnect-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
        at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:135)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.debezium.DebeziumException: java.lang.NullPointerException
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:79)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:118)
        ... 5 more
Caused by: java.lang.NullPointerException
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.createDataEvents(YugabyteDBSnapshotChangeEventSource.java:202)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:160)
        at io.debezium.connector.yugabytedb.YugabyteDBSnapshotChangeEventSource.doExecute(YugabyteDBSnapshotChangeEventSource.java:31)
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:70)
        ... 6 more`

**Comment by vrajat** [comment]
@codecrack3 The connector does not support snapshot yet. We are actively working on it and will message here once it is done. Can you tell us more about your setup? Are you using Kafka Connect or Confluent Cloud and what is the sink?

**Comment by codecrack3** [comment]
> @codecrack3 The connector does not support snapshot yet. We are actively working on it and will message here once it is done. Can you tell us more about your setup? Are you using Kafka Connect or Confluent Cloud and what is the sink?

@vrajat Thank you for responding. First, I'd want to provide you with some extra information.
   1. Can you tell us more about your setup? 
      - I have a yugabyte cluster that I want to sync with another yugabyte cluster using the debezium connector. However, I must use "snapshot.mode=initial" to sync all existing data in the old table. "
   3. Currently, I'm using Kafka connect

**Comment by vrajat** [comment]
Have you considered using xcluster feature? https://docs.yugabyte.com/preview/architecture/docdb-replication/async-replication/#overview

**Comment by vaibhav-yb** [comment]
Hi @codecrack3 We have added the support for `snapshot.mode=initial` and have released a new jar for the same as well. It's there in our GitHub releases and can be accessed at https://github.com/yugabyte/debezium-connector-yugabytedb/releases/tag/v1.7.0.11-BETA

Please give it a try and let us know your feedback on the same.

**Comment by codecrack3** [comment]
> Hi @codecrack3 We have added the support for `snapshot.mode=initial` and have released a new jar for the same as well. It's there in our GitHub releases and can be accessed at https://github.com/yugabyte/debezium-connector-yugabytedb/releases/tag/v1.7.0.11-BETA
> 
> Please give it a try and let us know your feedback on the same.

Thanks you very much for fix this issue. I’m going to check and feedback for you asap.
